server:
  port: 8085

spring:
  application:
    name: CONFIGSERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/KiranDaud221122/Hotel-Rating-Microservice-Config-Server
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always