server:
  port: 8082

spring:
  application:
    name: HOTELSERVICE

  config:
    import: optional:configserver:http://localhost:8085

  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: Kiran@2211
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


okta:
  oauth2:
    issuer: https://integrator-8521026.okta.com/oauth2/default
    audience: api://default